### ISSUE TITLE
ChinaDNS-NG 2.0

### ISSUE THREAD

**Issue by zfl9** [zfl9/chinadns-ng#144]
为减少 DNS 工具链的“套娃”，提高 chinadns-ng 的易用性，计划开发 ~~1.0~~、2.0 版本。

---

1.0 版本要实现的功能 (已完成，见 2024.03.07 版本)：

- [x] 支持 TCP + UDP 监听，尽量符合相关 RFC 规范
- [x] 支持多个监听 IP 地址，方便 IPv4 + IPv6 双栈等用例
- [x] 支持 TCP + UDP 上游，处理方式类似 dnsmasq，但可能会有所增强（如：强制 TCP 上游或 UDP 上游）
- [x] 每个上游组允许配置多个 DNS（超过 2 个），允许混用多个不同协议的 DNS 上游（TCP、UDP）
- [x] 引入配置文件支持，语法类似 dnsmasq，一行一个长选项

---

2.0 版本要实现的功能：

- [x] 支持 DNS 缓存，支持缓存白名单（不被缓存的域名），支持 stale 缓存模式。
- [x] 缓存 tag:none 域名的判定结果，减少不必要的转发/判定，减少 DNS 泄露。
- [x] 支持读取 hosts 文件（本地 A/AAAA 记录），支持定义本地 A/AAAA 记录。
- [x] ~~考虑支持 DNS over HTTPS 上游（可选的，不带 DoH 的可能称为 lite 版）~~
- [x] `--cache-stale` 参数最大值调整，目前最大是 65535（u16），某些情况下不太够
- [x] 允许过滤具有某些 qtype 的查询消息，如 qtype=64/65，用于某些特殊需求 [#82](/zfl9/chinadns-ng/issues/82)
- [x] **必要的** dnsmasq 类似功能（`--server`、`--ipset`、~~定义其他类型的 DNS 记录~~）
- [x] `tcp://` 上游增加 pipeline 长连接支持，目前是采用的是 tcp 短连接 [#151](/zfl9/chinadns-ng/issues/151)
- [x] 支持 DNS over TLS 上游（会发布两种版本，不需要此功能的请选 lite 版）
- [ ] add ip to ipset/nftset 时，允许指定 element 级别的 timeout 参数 [#155](/zfl9/chinadns-ng/issues/155)
- [x] ~~支持定义其他类型的本地 DNS 记录，如 SRV~~ （有需求请单独开 issue）

---

预计将使用单个 chinadns-ng 进程，替代 **经典用例** 下的 `dnsmasq + chinadns-ng + dns2tcp/dnsproxy` 组合。

**Comment by InspoOnU** [comment]
dnsmasq还有一个功能是提供本地PTR查询，可以通过查询DHCP(v6)的租约文件实现

**Comment by zfl9** [comment]
> dnsmasq还有一个功能是提供本地PTR查询，可以通过查询DHCP(v6)的租约文件实现

这个功能涉及到 DHCP 领域，暂不考虑哈。

**Comment by Smallthing** [comment]
#119 有望进入2.0吗，感谢
不是催更，就问问

**Comment by zfl9** [comment]
记录下目前的进度和情况

大概有一个月的时间都花在了折腾zig的构建系统(build.zig)、开发环境、交叉编译等一系列问题。好在这些问题都解决的差不多了。

最近一周总算开始写zig逻辑代码了，zig写起来还是挺舒服的，确实解决了C语言的许多痛点。comptime特性很好用，比C++的模板好太多了。

比如，我利用zig的comptime写了个printf格式字符串的检查例程，实现了类似gcc/clang对format参数的编译时检查功能。

希望此次zig之旅能够顺利，哈哈。

**Comment by xtccc** [comment]
> 记录下目前的进度和情况
> 
> 大概有一个月的时间都花在了折腾zig的构建系统(build.zig)、开发环境、交叉编译等一系列问题。好在这些问题都解决的差不多了。
> 
> 最近一周总算开始写zig逻辑代码了，zig写起来还是挺舒服的，确实解决了C语言的许多痛点。comptime特性很好用，比C++的模板/constexpr/consteval好太多了。
> 
> 比如，我利用zig的comptime写了个printf格式字符串的检查例程，实现了类似gcc/clang对format参数的编译时检查功能。
> 
> 希望此次zig之旅能够顺利，哈哈。

牛的，我前段时间无聊。自己用golang写了一个功能类似的dns 工具，先用着 。期待chinadns2.0

**Comment by xtccc** [comment]
这是我自己写dns时候的一点想法，作者看看有没有价值
我的ss-tproxy用的chnroute 模式
前两个是照抄chinadns-ng的，第三个是我根据自己的需求思考的

- [x] 白名单内的域名: dns 解析使用223.5.5.5 , 直接访问ip
- [x] 黑名单内的域名: dns 解析使用1.1.1.1 , 使用代理访问ip
- [x] 对于vps的域名处理: dns 解析使用 1.1.1.1 , 使用直连访问ip
      域名在黑名单里, ip地址在白名单里
      新建立一个文件vps_doamins.ext 记录vps的域名，如果dns 查询域名是vps域名，则不将其ip加入sstp_black[6]中,而是将其ip地址添加到sstp_white[6]中

**Comment by zfl9** [comment]
第三点，你想使用 remote-dns 解析 vps 域名，是怕国内 dns 污染？除此之外还有其他作用吗？

**Comment by xtccc** [comment]
> 第三点，你使用 remote-dns 来解析 vps 域名，是怕国内 dns 污染？
> 
> 除此之外还有其他作用吗？

就是怕污染，也是怕dns泄露之类的吧，
也是本地ssh访问vps服务器的时候不会走代理，不然会是好几个rtt

**Comment by zfl9** [comment]
仔细想了下，如果将 name:tag 再细分一下，那么应该可以满足更多需求（比如你这个）。

现有的 3 种 tag：

- `tag:none`：默认tag，可通过 -d/--default-tag 修改，没有关联的域名列表txt
- `tag:chn`：使用 -m/--chnlist-file 指定域名列表txt，若指定了add-tagchn-ip，则添加结果ip到ipset/nftset
- `tag:gfw`：使用 -g/--gfwlist-file 指定域名列表txt，若指定了add-taggfw-ip，则添加结果ip到ipset/nftset

-m/-g 域名列表txt的格式是：每行一个域名(后缀)

如果允许新增一个特殊语法，比如：

```
google.com
youtube.com
.forward_only my-vps.xxx.com
.forward_only my-vps2.xxx.com
```

因为正常域名不会以 . 开头，所以我想这是安全的，这里的 forward_only 表示这些域名在启用了 add-tag[gfw|chn]-ip 的情况下，不会进行 add-ip to ipset/nftset 逻辑，tag属性只用于转发判定。

**Comment by zfl9** [comment]
> 这是我自己写dns时候的一点想法，作者看看有没有价值 我的ss-tproxy用的chnroute 模式 前两个是照抄chinadns-ng的，第三个是我根据自己的需求思考的
> 
> * [x]  白名单内的域名: dns 解析使用223.5.5.5 , 直接访问ip
> * [x]  黑名单内的域名: dns 解析使用1.1.1.1 , 使用代理访问ip
> * [x]  对于vps的域名处理: dns 解析使用 1.1.1.1 , 使用直连访问ip
>   域名在黑名单里
>   新建立一个文件vps_doamins.ext 记录vps的域名，如果dns 查询域名是vps域名，则不将其ip加入sstp_black[6]中,而是将其ip地址添加到sstp_white[6]中

---

> 如果dns 查询域名是vps域名，则不将其ip加入sstp_black[6]中,而是将其ip地址添加到sstp_white[6]中

第一点（不加入黑名单的ipset）通过上面的扩展应该满足了
第二点（加入白名单的ipset）还需要再讨论讨论

**Comment by xtccc** [comment]
> > 这是我自己写dns时候的一点想法，作者看看有没有价值 我的ss-tproxy用的chnroute 模式 前两个是照抄chinadns-ng的，第三个是我根据自己的需求思考的
> > 
> > * [x]   白名单内的域名: dns 解析使用223.5.5.5 , 直接访问ip
> > * [x]   黑名单内的域名: dns 解析使用1.1.1.1 , 使用代理访问ip
> > * [x]   对于vps的域名处理: dns 解析使用 1.1.1.1 , 使用直连访问ip
> >   域名在黑名单里
> >   新建立一个文件vps_doamins.ext 记录vps的域名，如果dns 查询域名是vps域名，则不将其ip加入sstp_black[6]中,而是将其ip地址添加到sstp_white[6]中
> 
> 为什么要解析VPS的域名呢? 有两个可能
> 
> 1. 你的 vps 不是静态ip?
> 2. 你用的 trojan/websocket类似的代理协议?
> 
> 对于第一点, 可能没什么好办法咯.
> 
> 对于第二点, 这些协议都可以 服务器填ip, 然后sni/servername的地方填域名, 这样`代理客户端连接代理服务端`就不需要解析你的域名 (我猜测这是你想解决的问题). 然后对于其他程序访问你的vps域名, 你可以把你的域名映射到 hosts里面去.

手机什么的没有hosts 
本质上我是既要ip的直连又要域名的国外解析，你想想这个

**Comment by zfl9** [comment]
本质上来说，之所以不能简单的实现你的需求，是因为 tag:gfw 和 tag:chn 承担了两个角色：

- 转发给特定上游dns
- 将域名解析结果加入ipset/nftset

如果我们将这两个功能拆分开，那么问题就迎刃而解。也即，将它们分别对应两个域名列表txt：

- forward-to-upstream.txt：用于查询时的转发判定
- add-ip-to-set.txt：用于响应时的添加ip至set

考虑到绝大多数 tag:chn、tag:gfw 域名都需要执行上述两种功能（也即转发判定，结果ip添加至set），为了方便（也主要是考虑到程序效率，以及兼容老的chinadns-ng），可以给 chinadns-ng 新增一个选项，比如：

`--special-domains <file>`，文件格式类似 ini，比如这样：

```ini
[forward.china]
xxx.com
...

[forward.trust]
yyy.com
...

[add-ip.china]
aaa.com
...

[add-ip.trust]
bbb.com
...
```

预计这个文件不会很大，最多十几个域名，因为绝大部分域名都可以使用原有的 --gfwlist-file/--chnlist-file 功能。

**Comment by zfl9** [comment]
chinadns-ng 2.0 准备加入配置文件支持，因为目前选项有点多了，使用配置文件会好一点，起码看起来清爽许多。

也许另一个选择是不添加上述说的 `--special-domains <file>` 选项，而是添加几个更简单的选项来搞定，因为可以将选项放到配置文件（chindns.conf），所以本质上也差不多，也就是类似这样：

chinadns.conf 配置文件，语法简单，也是一行一个（长）选项，空行和井号开头的行被忽略

```bash
# 监听地址和端口
bind-addr 127.0.0.1
bind-port 65353

# china上游，可以重复指定，也支持传统的逗号隔开
china-dns 223.5.5.5
china-dns 119.29.29.29

# trust上游，同上
trust-dns 8.8.8.8
trust-dns 1.1.1.1

# 域名列表文件，因为文件很大，所以用单独txt存储
chnlist-file /path/to/chnlist.txt
gfwlist-file /path/to/gfwlist.txt

# ipset相关
add-tagchn-ip
add-taggfw-ip gfwip,gfwip6
ipset-name4 chnroute
ipset-name6 chnroute6

# 特殊域名（也就上面讨论的）
#
# 转发给china上游的
forward-china xxx.com
forwrad-china xyz.com
#
# 转发给trust上游的
forward-trust abc.com
forward-trust foo.com
#
# 添加到chinaip集合的(add-tagchn-ip)
add-ip-china bar.com
add-ip-china baz.com
#
# 添加到trustip集合的(add-taggfw-ip)
add-ip-china yyy.com
add-ip-china ppp.com

# 其他选项...
verbose
```

**Comment by zfl9** [comment]
总结一下，可以通过新增 4 个更细分的 命令行选项/配置 来满足这种特别的需求：

- `--forward-china 域名`：等价于 --chnlist-file 中的域名，但仅限于 forward 上下文。
- `--forward-trust 域名`：等价于 --gfwlist-file 中的域名，但仅限于 forward 上下文。
- `--add-ip-china 域名`：等价于 --chnlist-file 中的域名，但仅限于 add-ip 上下文。
- `--add-ip-trust 域名`：等价于 --gfwlist-file 中的域名，但仅限于 add-ip 上下文。

注意，如果未启用 `--add-tagchn-ip`，则 `--add-ip-china` 没有实际效果；同理，如果未启用 `--add-taggfw-ip` 则没有实际效果。（当然，如果能从头来过，将 命令行选项 重新规划/细分下，其实就不会有这个限制了。不过考虑到现状以及现实需求，目前这个小限制应该无伤大雅）。

**Comment by kuyagic** [comment]
提一个疑问

如果配置文件里 没有指定 ipset 相关的配置 也就是国内 国外的 2个 txt 里的 只是区分了 转发的目标 并不会加入对应的ipset, 然后 上面说的这个其实和 txt 里写域名等效了 对吧?

**Comment by zfl9** [comment]
> 提一个疑问
> 
> 如果配置文件里 没有指定 ipset 相关的配置 也就是国内 国外的 2个 txt 里的 只是区分了 转发的目标 并不会加入对应的ipset, 然后 上面说的这个其实和 txt 里写域名等效了 对吧?
 

是的，如果未指定 add-ip 操作，那么 `--forward-china`、`--forward-trust` 也等价于 `-m chnlist.txt` `-g gfwlist.txt`。这种情况下，`--add-ip-china`、`--add-ip-trust` 没有效果。

**Comment by kuyagic** [comment]
有没有打算做一个 广告域名的 配置呢? 
如果有 我这边可以少一层套娃.

**Comment by zfl9** [comment]
如果广告域名是类似 gfwlist.txt/chnlist.txt 这样的域名后缀，那么应该很简单。但是如果涉及到正则表达式等模式，那么不会考虑。

但我不清楚通过 dns 过滤广告的效果如何，我觉得很多广告都是内嵌到网页里面的，仅在 域名解析 这个粗粒度进行过滤，感觉不是非常理想。

**Comment by kuyagic** [comment]
> 如果广告域名是类似 gfwlist.txt/chnlist.txt 这样的域名后缀，那么应该很简单。但是如果涉及到正则表达式等模式，那么不会考虑。
> 
> 我不清楚通过 dns 过滤广告的效果如何，我觉得很多广告都是内嵌到网页里面的，仅在 域名解析 上动手，感觉不是非常理想。我很久之前也折腾过类似的基于 dns 的广告过滤（当然，并不是 AdGuardHome 哈），不过后来我还是用浏览器插件了。

总之目前我还是插件. dns级别 需求其实不是非常高 多谢解答

**Comment by muziling** [comment]
碰到 了一个见鬼的域名s5.m3u8.cool，只能附加部分地区的ecs才行，比如cloudcone就解析不到IP，oracle韩国可以，  oracle美国好像不行。

chinadns-ng会有这功能吗？   目前只有mosdns能满足需求

**Comment by zfl9** [comment]
> 可能部分用户还有另一个需求，就是腾讯的域名用腾讯的DNS解析，解决微信转圈的问题

你直接使用腾讯的 119.29.29.29 作为 china 上游组，应该就可以了吧？

如果你的意思是让 chinadns-ng 能够为 特定域名 使用单独的 dns 上游，如 腾讯域名列表(tencent.txt) 使用 腾讯DNS上游(119.29.29.29)，那可能永远不会支持，因为 chinadns-ng 的核心就是两组 DNS 上游（china + trust），如果要进行这种更改，则将违反核心设计。

另外，我似乎没有遇到过你说的微信转圈问题（也许是部分地区？或者特殊网络环境？），如果这种情况很普遍，那岂不是说腾讯/微信相关的域名必须使用腾讯自己的DNS？（我认为不大可能，否则除了腾讯DNS外的其他公共DNS不都得废？）

**Comment by zfl9** [comment]
> 还要能支持 kms的 _vlmcs._tcp 吧

这个我看了下，核心是让 chinadns-ng 支持创建 SRV 记录，响应相关查询。

目前来说不确定是否要支持，等 2.0 完成了再看看吧。

**Comment by zfl9** [comment]
还是想重申下，chinadns-ng 2.0 虽然会考虑实现一些较为常用的功能，但目的不是替换 dnsmasq。

我仍然想让 chinadns-ng 保持简单和愚蠢，如果有些特殊需求无法满足，那我只能表示抱歉，希望大家理解。

**Comment by muziling** [comment]
只是看到写了2.0的目标是
替代传统的 dnsmasq + chinadns-ng + dns2tcp/dnsproxy 组合

所以最终还是要dnsmasq + chinadns-ng 2.0套娃，微信转圈只是举了一个例子，有的人可能和公司搞了穿透，公司域名要用公司的DNS解析。

**Comment by zfl9** [comment]
> 2.0 预计将使用单个 chinadns-ng 进程，替代经典用例下的 `dnsmasq + chinadns-ng + dns2tcp/dnsproxy` 组合。

嗯，确实描述不当，我做了修改：

之前：2.0 预计将使用单个 chinadns-ng 进程，替代传统的 dnsmasq + chinadns-ng + dns2tcp/dnsproxy 组合。

现在：2.0 预计将使用单个 chinadns-ng 进程，替代**经典用例**下的 dnsmasq + chinadns-ng + dns2tcp/dnsproxy 组合。

**Comment by zfl9** [comment]
> 只是看到写了2.0的目标是 替代传统的 dnsmasq + chinadns-ng + dns2tcp/dnsproxy 组合
> 
> 所以最终还是要dnsmasq + chinadns-ng 2.0套娃，微信转圈只是举了一个例子，有的人可能和公司搞了穿透，公司域名要用公司的DNS解析。

我思考了下，在设计上确实可以再优化下，考虑到之前提出的几个新选项：

> --forward-china 域名：等价于 --chnlist-file 中的域名，但仅限于 forward 上下文。
--forward-trust 域名：等价于 --gfwlist-file 中的域名，但仅限于 forward 上下文。
--add-chnip 域名：等价于 --chnlist-file 中的域名，但仅限于 add-ip 上下文。
--add-gfwip 域名：等价于 --gfwlist-file 中的域名，但仅限于 add-ip 上下文。

我认为可以这样，让 chinadns-ng 支持部分 dnsmasq 功能（比如 --server、--ipset、--nftset），满足你们说的这些特殊需求，这样就不必增加之前提到的 --forward-*、--add-*ip 选项了，并且会让 chinadns-ng 更灵活，容易扩展。

chinadns-ng 只针对 chnlist/gfwlist.txt 进行性能优化（也就是现在做的这样），因为此类域名很多，优化是非常值得且必要的；

而对于其他 dnsmasq 的功能，则进行常规实现（类似 dnsmasq），因为这些肯定不存在大量域名，没必要花时间做深度优化。

**Comment by zfl9** [comment]
2.0 的开发时间可能会比预计的长，因为我需要先用 Zig 将当前的大部分 chinadns-ng 功能重写掉，基本的功能/性能测试通过后，才会着手 2.0 的改造。因此 2.0 的目标仍然未最终确定，大家有什么想法也欢迎提出。

**Comment by zfl9** [comment]
> udp 包过长会落到 tcp？

按我的理解，fallback 由 dns query 发起端执行，中间的 forwarder 透传 req/resp 就行，不用关心 TCP fallback。

**Comment by zfl9** [comment]
>    In addition, it is noted that all recursive and authoritative servers MUST send responses using the same transport as the query arrived on. In the case of TCP, this MUST also be the same connection.

> Stub resolvers and recursive resolvers MAY elect to send either TCP or UDP queries depending on local operational reasons.  TCP MAY be used before sending any UDP queries.  If the resolver already has an open TCP connection to the server, it SHOULD reuse this connection.  In essence, TCP ought to be considered a valid alternative transport to UDP, not purely a retry option.

**Comment by zfl9** [comment]
简单来说，对于 chinadns-ng (dns forwarder)，如果一个 query 是从 TCP 端口(连接)接收到的，那么应该用相同的 TCP 连接向查询方返回 response；如果一个 query 是从 UDP 端口接收到的，那么应该使用 UDP 传输方式向查询方返回 response。

在转发时，chinadns-ng 可以根据配置，自由的选择向 TCP 上游、UDP 上游转发接收到的 query。这也是此 issue 开头提到的：`支持 TCP + UDP 上游，处理方式类似 dnsmasq，但可能会有所增强（如：强制 TCP 上游或 UDP 上游）`

**Comment by zfl9** [comment]
暂时是这样规划的：

- 先用 Zig 重写大部分 C 代码（有些 C 代码也许需要等到 Zig 成熟之后，才会重写）
- 在此基础上，实现开头提到的部分高优先级功能：TCP监听、TCP上游、配置文件（也许应命名为 1.0，并且会先合并到 master，作为正常 release 版本发布）
- 在上述 1.0 的基础上，实现剩下的功能：DNS缓存、DoH支持（依赖OpenSSL，是可选功能，不支持DoH的称为lite版本），以及其他 常用的/必要的 dnsmasq 类似功能。

**Comment by InspoOnU** [comment]
将返回国内/国外IP的域名分别缓存起来，避免重复请求。这个功能可行吗？

**Comment by zfl9** [comment]
> 将返回国内/国外IP的域名分别缓存起来，避免重复请求。这个功能可行吗？

什么意思，没懂？具体点？

**Comment by zfl9** [comment]
等2.0版本加入dns缓存功能后，再看看吧，我觉得dns缓存可以很大程度上缓解你说的问题：重复请求、dns泄露。

当然缓存过期那就是另一回事了；另外，这里仍然有操作空间，比如可以加个小优化，tag:none域名的转发“目标”可以缓存起来，并且可以设置不过期（与TTL无关），是不是就达到了你说的全部目的？

**Comment by InspoOnU** [comment]
> 等2.0版本加入dns缓存功能后，再看看吧，我觉得dns缓存可以很大程度上缓解你说的问题：重复请求、dns泄露。
> 
> 在实现了DNS缓存的前提下，可以加个小优化，将tag:none域名的转发“目标”缓存起来（这个数据不会过期，与TTL无关，并且只缓存“转发目标”，也就是一个bool值：之前是转发给china的还是转发给trust的），这样是不是就达到了你说的全部目的？

这样设计可以，完全达到了

**Comment by zfl9** [comment]
@mm11253 拒绝连接是因为 chinadns-ng 目前还没实施 tcp 监听。用 zig 重写的 1.0/2.0 版本已经加入 tcp 支持了。

结合你引用的几个 issue 推测，有这几方面的原因：

1. 上游未遵循 EDNS 的 udp bufsz 扩展信息，你给出的示例显示 dig 的 bufsz 是 1232 字节，即使超过 512 字节的响应，也不应该设置 TC 标志，因为实际缓冲区大小是 1232 字节，并不会“截断”
2. 上游未实施 DNS 域名压缩导致响应消息比较大，容易超出传统的 512 字节限制，而又由于第 1 条原因，导致很多“不必要的截断，然后通过 TCP 重试”的行为
3. chinadns-ng 目前尚未支持 TCP 监听/上游，导致 dig（查询客户端）在收到带 TC 标志的udp响应后，通过 tcp 重试查询时，未能连接上 chinadns-ng，于是出现连接被拒，查询超时。

**Comment by zfl9** [comment]
更新下进度，1.0版本已基本完成，测试了几天，暂未发现问题。

快的话这几天会更新master分支、README、发布1.0的release版本。

**Comment by muziling** [comment]
想了下，好像和dnsmasq套娃是必须的， 所以实不实现dnsmasq的功能好像都没关系，  路由器需要dnsmasq来提供DHCP服务。
最终方案都是 dnsmasq + chinadns-ng

**Comment by zfl9** [comment]
> 想了下，好像和dnsmasq套娃是必须的， 所以实不实现dnsmasq的功能好像都没关系， 路由器需要dnsmasq来提供DHCP服务。 最终方案都是 dnsmasq + chinadns-ng

路由器上，你说的是有道理的。

但不是所有人都在（主）路由器上使用，所以实现某些**常用/必要**功能仍然有意义。

**Comment by xtccc** [comment]
> 想了下，好像和dnsmasq套娃是必须的， 所以实不实现dnsmasq的功能好像都没关系，  路由器需要dnsmasq来提供DHCP服务。
> 最终方案都是 dnsmasq + chinadns-ng 

也不一定吧，我现在使用systemd-netorkd 的dhcp server，用着也还可以

**Comment by zfl9** [comment]
见最新 2024.03.25 版本，新增了以下功能：
- DNS 缓存、缓存忽略、缓存预刷新等。
- tag:none 域名的判定结果缓存。

**Comment by zfl9** [comment]
计划有变，由于 DoH 最低推荐 HTTP/2，纯手撸一个 HTTP/2 客户端不现实，看了其他实现，要么是使用语言(标准库)自带的 http 库，要么是使用第三方库（如 libcurl）；C/Zig 没有自带的 http 库。

也看了一些有关 DoH 和 DoT 的讨论，最终决定使用 DoT，相比较 DoH，少了一层 http 协议，可以减少协议开销。

想了下，浏览器更“喜欢” DoH 是因为浏览器本身就有完备的 HTTPS 客户端支持，而其他更底层的实现（如 systemd-resolved）则更偏好于 DoT，虽然不知道具体原因，但肯定有很大一部分是 HTTP/2 协议带来的复杂度导致的。

关于 DoH 和 DoT 的争论，主要是这一点：

- DoH 使用 443 端口，可藏匿于常规 HTTPS 流量中
- DoT 使用 853 端口，相比较 HTTPS/443，更容易被识别

不过我想说的是，真想找出哪些是 DoH 流量，哪些是 HTTPS 流量，太简单了，直接 ip 识别即可（dst_ip=公共DNS && dst_port=443），所以这个观点站不住脚；更何况 DoH 流量的数据包大小明显不同于常规网站 HTTPS 的数据包大小。

也就是说，国内DNS“藏不住”，国外DNS没必要藏（反正都走了代理）。

**Comment by zfl9** [comment]
#157

**Comment by zfl9** [comment]
> 这是我自己写dns时候的一点想法，作者看看有没有价值 我的ss-tproxy用的chnroute 模式 前两个是照抄chinadns-ng的，第三个是我根据自己的需求思考的
> 
> * [x]  白名单内的域名: dns 解析使用223.5.5.5 , 直接访问ip
> * [x]  黑名单内的域名: dns 解析使用1.1.1.1 , 使用代理访问ip
> * [x]  对于vps的域名处理: dns 解析使用 1.1.1.1 , 使用直连访问ip
>   域名在黑名单里
>   新建立一个文件vps_doamins.ext 记录vps的域名，如果dns 查询域名是vps域名，则不将其ip加入sstp_black[6]中,而是将其ip地址添加到sstp_white[6]中

已实现，使用自定义组即可，自由搭配 upstream、ipset/nftset。

**Comment by zfl9** [comment]
没有这个计划。

什么需求会要用到正则？

**Comment by zfl9** [comment]
> 我看到一些能找到的 gfwlist 文件是用 AutoProxy 写的，里面很多会用到正则表达式，如果做转换为 chinadns-ng 支持的格式比较麻烦。

这个大可不必担心，有很多成熟的 gfwlist2dnsmasq 工具，也有很多现成的 gfwlist.txt 域名列表。它们会处理正则表达式（一般也就是 `google.*`、`blogspot.*`，都是可以简单枚举出来的）。

---

chinadns-ng 的 dnl（domain name list，域名列表），里面配置的是 “域名后缀”。模式 `xxx.com` 可以匹配：

- `xxx.com`
- `a.xxx.com`
- `b.a.xxx.com`
- `c.b.a.xxx.com`
- 以此类推

**Comment by zfl9** [comment]
2.0 已完成，见最新 2024.04.27 版本。其他问题请单独开 issue 讨论。

**Comment by Karmylr** [comment]
> 记录下目前的进度和情况
> 
> 大概有一个月的时间都花在了折腾zig的构建系统(build.zig)、开发环境、交叉编译等一系列问题。好在这些问题都解决的差不多了。
> 
> 最近一周总算开始写zig逻辑代码了，zig写起来还是挺舒服的，确实解决了C语言的许多痛点。comptime特性很好用，比C++的模板/constexpr/consteval好太多了。
> 
> 比如，我利用zig的comptime写了个printf格式字符串的检查例程，实现了类似gcc/clang对format参数的编译时检查功能。
> 
> 希望此次zig之旅能够顺利，哈哈。

能不能说下zig解决了c的哪些痛点

**Comment by zfl9** [comment]
> 能不能说下zig解决了c的哪些痛点

C 的定位其实是“可移植的汇编语言”，因此 C 不可能有太多语言方面的更改（看看 C11、C17、C23 就明白了）。

作为 C 程序员，我一直在寻找另一门“更现代”的 C 语言，它具有与 C 一样的简单性（显然 C++、Rust 并不“简单”）、高性能（带 GC 的语言首先被排除，比如 Go），因此我找到了 Zig。

正如官网以及很多博客所说，Zig 致力于打造一门更现代的 C 语言。但就目前来看，Zig 还不足以完全替代 C，长远来看，也不可能取代 C，与 C/C++ 共存应该是一个比较理想的情况。而且 Zig 目前的热度一般，距离 Zig 1.0 也还有许多工作要做，我相信多数人都是因为 `zig cc/c++` 编译工具链 接触的 Zig，我也不例外。

下面来说说 Zig 解决了什么问题（都是我个人的实际使用体验）：

- 更严格的编译时检查、运行时检查（Debug/Safe构建模式），能避免不少低级错误，对问题排查也更友好。
- 指针类型细分：单对象指针、多对象指针（长度未知）、切片（多对象指针+长度）、哨兵终止的多对象指针/切片。
- 数组是值类型，不会像 C 那样自动退化为指针。
- 有原生的向量类型（SIMD），虽然我目前还没用过。
- 好用的 comptime，比 C++ 模板那套优雅的多，条件编译、泛型都是常规 Zig 语法，不再是晦涩的模板语言。
- 比 C 更丰富的标准库，不过目前还不够成熟和稳定，我目前仍然使用 C 库为主，仅使用 Zig 的数据结构/算法。
- 自带构建系统（zig build），构建系统是用 Zig 描述的，而不是其他语言（Shell、Makefile、CMakeLists.txt）。
- 自带完善的交叉编译工具链，自带 C、C++ 编译器，自带 musl 源码库，这是 Zig 可以与 C/C++ 无缝集成的基础。
- 可以直接导入 C 头文件（原理是将头文件中的 C 源码翻译为 Zig 源码，并且可以识别大部分的宏），而不是依赖 FFI。
- 没有默认初始化（如初始化为 0），所有初始化都是显式的。
- optional 类型、optional 指针。
- 错误处理比较优雅，尤其是对比 C、Go。
- 没有隐式的控制流，代码容易阅读，比如标准库的可读性就很不错（因为缺少文档，我直接都是看源码）。
- 任意位宽的整数类型（`i1 ~ i65535`、`u1 ~ u65535`）
- 和 lua “一切皆 table”一样，Zig 也可以笼统的说“一切皆 struct”，因为 Zig 源文件也是一个 struct。
- 枚举字面量（Enum Literals）很好用，可以省略 Enum 类型前缀，清爽，舒服。
- 块级别的 defer，可以很大程度取代 C 中 Goto 的使用场景（退出时进行“清理”操作）。
- 一切皆表达式，可以给块（block）打 label，这样块就可以有“返回值”了（有点类似立即运行的匿名函数）。
- 异步语法糖（这是我打算用 Zig 重写 ChinaDNS-NG 的最根本原因），但目前异步在自托管编译器中尚未回归。

缺点，或者说有些让我感到不爽的地方：

// TODO，等会再更新。

**Comment by Karmylr** [comment]
@zfl9 comptime比constexpr和consteval好在哪呢

**Comment by zfl9** [comment]
comptime 基本等于 C++ template + consteval + constexpr，而且 comptime 是常规 zig 语法。

另外，zig 有编译时的反射：`@Type`、`@typeInfo()`，这在 C++ 里面是没有的。

**Comment by lwintermelon** [comment]
@zfl9
>缺少对结构体布局的细微控制（只有 packed struct），缺少位域（对于定义网络协议很有用，特别是 DNS）。

 这个[讨论](https://github.com/ziglang/zig/issues/12852#issuecomment-1536752144)你有注意到吗，期待有更好的解决方案和命名。

**Comment by zfl9** [comment]
是的，我赞同了这个评论。zig 确实需要更强大的类型建模能力。虽然现在勉强能满足，但略微繁琐。
