### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zfl9** [zfl9/chinadns-ng#178]
- [ ] 跟进 zig 上游的更新，始终保持最新的 zig 工具链。
- [ ] 由于 zig 版本更新，需要手动编码实现 async 异步语义。
- [ ] 重写剩下的 C 模块，目标是 100% zig code（除了 libc、wolfssl）。

---

UPDATE: 

用 zig 手动模拟 suspend/resume 不太现实，除非是最简单的异步代码。对于那些存在 条件分支、循环 等构造的异步代码，根本无法实现。因为 zig 没有 goto（C 的 switch/case 本质就是 goto，著名的 `Duff's device` 就是利用它实现的）。

主要技术困难在于 resume，resume 的核心就是 重新进入之前被 suspend 的异步函数，并 jmp 至上次的暂停点之后，继续执行后面的代码。在没有 goto（或者 C 的 switch/case）的情况下，不可能用常规 zig 代码实现，只能借助编译器。

---

~~我在犹豫是否要回到 C（将 zig 作为 build system，编译工具链，zig 随时保持最新）~~，还是继续用 zig 0.10.1，静等 zig 更新。

**Comment by hawkbee** [comment]
是否会考虑集成异步事件库，虽然可读性会差一些，好处是可以不依赖于语言特性，类似：

[libxev](https://github.com/mitchellh/libxev)
[zig-aio](https://github.com/Cloudef/zig-aio)

**Comment by zfl9** [comment]
通用事件循环库会带来更多代码和开销，更重要的是，chinadns-ng 在设计上就是在 linux 上运行的（ipset/nftset）。

因此通用事件循环库就没有必要了，因为我只需要考虑 epoll API，目前的 EvLoop.zig 就是对它的极简封装（只有必要功能）。

**Comment by zfl9** [comment]
现在我也准备不依赖 async 语言特性了，改为自己手动实现（状态机）。
除非后面打算跨平台（也许永远不会），才会引入 libev 这样的轻量级 C 事件库。

**Comment by hawkbee** [comment]
嗯，跨平台不是优先项，事件库就是抽象了一层，方便适配，比如现在linux又有io_uring了，适配支持就可以在抽象层之上了

**Comment by hapood** [comment]
期待能早日完工，我有空也学习下zig语言，希望以后可以一起改进这个项目。
